#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servo[servo1] = 135;
  return;
}

void setDriveMotors(int targetLeft, int targetRight)
{
	//int currentLeft = motor[leftMotor],
	//		currentRight = motor[rightMotor],
	//		incrLeft = (targetLeft > currentLeft) ? 1 : -1,
	//		incrRight = (targetRight > currentRight) ? 1 : -1;
	//bool leftDone = false, rightDone = false;
	//while (!(leftDone && rightDone)) {
	//	if (!leftDone)
	//	{
	//		currentLeft += incrLeft;
	//		motor[leftMotor] = currentLeft;
	//		if (currentLeft == targetLeft) leftDone = true;
	//	}
	//	if (!rightDone)
	//	{
	//		currentRight += incrRight;
	//		motor[rightMotor] = currentRight;
	//		if (currentRight == targetRight) rightDone = true;
	//	}
	//	wait1Msec(2);
	//}
	motor[rightMotor] = targetRight;
	motor[leftMotor] = targetLeft;
}

void stopDriveMotors()
{
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  //waitForStart();   // wait for start of tele-op phase

  int leftRight, forwardBack;
	bool down = false;

	int targetLeft, targetRight, currentLeft, currentRight;

	int i = 0;

  while (true)
  {
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.

  	getJoystickSettings(joystick);
		//servo
		if (joy1Btn(6) == 1) {
			down = false;
		} else if (joy1Btn(5) == 1) {
			down = true;
		}
		if (down)
		{
			servo[servo1] = 128;
		}
		else
		{
			servo[servo1] = 255;
		}
		//motors
		leftRight = joystick.joy1_x2;
		forwardBack = -joystick.joy1_y1;
		if (abs(leftRight) > 15)
		{
			if (leftRight > 0)
			{
				targetLeft = 20;
				targetRight = -20;
			}
			else
			{
				targetLeft = -20;
				targetRight = 20;
			}
		}
		else if (abs(forwardBack) > 15)
		{
			if (forwardBack > 0)
			{
				targetRight = 80;
				targetLeft = 80;
			}
			else
			{
				targetRight = -80;
				targetLeft = -80;
			}
		}
		else
		{
			//currentLeft = 0;
			//currentRight = 0;
			targetLeft = 0;
			targetRight = 0;
		}
		if (i % 3 == 0)
		{
			if (currentLeft != targetLeft)
			{
				if (currentLeft > targetLeft)
				{
					currentLeft--;
				}
				else
				{
					currentLeft++;
				}
			}
			if (currentRight != targetRight)
			{
				if (currentRight > targetRight)
				{
					currentRight--;
				}
				else
				{
					currentRight++;
				}
			}
		}
		i++;
		setDriveMotors(currentLeft, currentRight);
  }
}
