#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors GyroSensor = (tSensors) S2;

const int offset = SensorValue(GyroSensor);

float k_l = 1, k_r = 1, s_l = 0, s_r = 0, reading = 0;

task MotorRegulation()
{
	while (true)
	{
		reading += ((float) SensorValue(GyroSensor)-offset) * 0.01;
		nxtDisplayBigTextLine(1, "%f", reading);
		k_l = (25.0 + reading) / 25.0;
		k_r = (25.0 - reading) / 25.0;
		motor[leftMotor] = k_l * s_l;
		motor[rightMotor] = k_r * s_r;
		wait1Msec(10);
	}
}

void setDriveMotors(int speed)
{
	s_l = speed;
	s_r = speed;
}

task main()
{
	StartTask(MotorRegulation);
	setDriveMotors(-20);
	wait1Msec(5000);
	setDriveMotors(0);
}
