#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     rightMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define margin_of_error 36
/* 	Surface	|	Error
		Carpet		20
		Concrete	43
		Wood			36
*/

const tSensors GyroSensor = (tSensors) S2;

const int offset = SensorValue(GyroSensor);

void turnRight(int angle)
{
	if (angle > 0)
	{
		motor[rightMotor] = 80;
		motor[leftMotor] = -80;
		angle -= margin_of_error;
	}
	else
	{
		motor[rightMotor] = -80;
		motor[leftMotor] = 80;
		angle += margin_of_error;
	}
	int lastReading = SensorValue(GyroSensor)-offset, currentReading;
	float total = 0;
	int interval = 2;
	while (true)
	{
		currentReading = SensorValue(GyroSensor)-offset;
		total += ((float) interval) / 1000.0 * (((float) currentReading + (float) lastReading) / 2);
		if (abs(total) > abs(angle))
		{
			break;
		}
		lastReading = currentReading;
		wait1Msec(interval);
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void turnLeft(int angle)
{
	turnRight(-angle);
}

task main()
{
	turnRight(90);
	wait1Msec(2500);
	turnLeft(90);
}
