#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors GyroSensor = (tSensors) S2;

const int offset = SensorValue(GyroSensor);

void turnLeft(float degrees)
{
	int i = 0;
	while (degrees > 0)
	{
		nxtDisplayBigTextLine(1, "%d", degrees);
		degrees -= ((float) (SensorValue(GyroSensor)-offset)) * 0.002;
		float motorSpeed = sin(((float) i) * 0.02)/2.0 + 1.0/2.0;
		motor[leftMotor] = -round(motorSpeed * 5);
		motor[rightMotor] = round(motorSpeed * 5);
		i++;
		wait1Msec(2);
	}
}

task main()
{
	turnLeft(90);
}
