#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAX_SPEED 5

const tSensors GyroSensor = (tSensors) S2;

const int offset = SensorValue(GyroSensor);

void turnLeft(float degrees)
{
	float degreesLeft = degrees, gyroReading;
	int motorSpeed;
	while (degreesLeft > 0)
	{
		motorSpeed = round((((float) MAX_SPEED) / pow(degrees, 6)) * pow(degreesLeft, 6)) + 1;
		motor[leftMotor] = -motorSpeed;
		motor[rightMotor] = motorSpeed;
		gyroReading = SensorValue(GyroSensor)-offset;
		degreesLeft -= gyroReading * 0.005;
		wait1Msec(5);
	}
}

task main()
{
	turnLeft(360);
}
