#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors GyroSensor = (tSensors) S2;

const int offset = SensorValue(GyroSensor);

void turnLeft(float degrees)
{
	float startTotal = 0, motorSpeed = 0;
	for (;motorSpeed <= 3; motorSpeed++)
	{
		motor[leftMotor] = -motorSpeed;
		motor[rightMotor] = motorSpeed;
		startTotal += ((float) (SensorValue(GyroSensor)-offset)) * 0.2;
		wait1Msec(200);
	}
	degrees -= startTotal;
	while (degrees > startTotal)
	{
		nxtDisplayBigTextLine(1, "%d", degrees);
		degrees -= ((float) (SensorValue(GyroSensor)-offset)) * 0.015;
		wait1Msec(15);
	}
	for(;motorSpeed >= 0; motorSpeed--)
	{
		motor[leftMotor] = -motorSpeed;
		motor[rightMotor] = motorSpeed;
		wait1Msec(200);
	}
}

task main()
{
	turnLeft(90);
}
