#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

task main()
{

	tHTIRS2 irSeeker;

	initSensor(&irSeeker, S3);

	int direction, strength;

	irSeeker.mode = DSP_1200;
	while (true)
	{
		readSensor(&irSeeker);
		direction = irSeeker.acDirection;
		strength = irSeeker.enhStrength;
		nxtDisplayBigTextLine(1, "%d", direction);
		nxtDisplayBigTextLine(3, "%d", strength);
		if (direction > 3) {
			motor[leftMotor] = 40;
			motor[rightMotor] = -40;
		} else if (direction < 1) {
			motor[leftMotor] = -40;
			motor[rightMotor] = 40;
		} else if (strength < 200) {
			motor[leftMotor] = -60;
			motor[rightMotor] = -60;
		} else {
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}
}
