#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed;
	for (speed = 0; speed <= 80; speed += 1)
	{
		motor[leftMotor] = speed;
		wait1Msec(100);
	}
	wait1Msec(2500);
	for (; speed >= 0; speed -= 1)
	{
		motor[leftMotor] = speed;
		wait1Msec(100);
	}
}
