#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	int x, y;
	while (true)
	{
		getJoystickSettings(joystick);
		x = joystick.joy1_x1 * 100/128 * 0.2;
		y = - joystick.joy1_y1 * 100/128 * 0.8;
		if (x < 0)
		{
			motor[motorRight] = y;
			motor[motorLeft] = y - abs(x);
		}
		else
		{
			motor[motorRight] = y - abs(x);
			motor[motorLeft] = y;
		}
		motor[motorLeft] = - motor[motorLeft];
	}
}
