#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	bFloatDuringInactiveMotorPWM = true;

	int x2, y1;
	while (true)
	{
		getJoystickSettings(joystick);
		x2 = -joystick.joy1_x2 * 80/128;
		y1 = joystick.joy1_y1 * 80/128;
		if (abs(x2) > abs(y1) && abs(x2) > 15)
		{
			motor[leftMotor] = x2;
			motor[rightMotor] = x2;
		}
		else if (abs(y1) > 15)
		{
			motor[leftMotor] = -y1;
			motor[rightMotor] = y1;
		}
		else
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}
}
