#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	servo[servo1] = 135;
	while(true) {
		getJoystickSettings(joystick);
		if (joy1Btn(1) == 1) {
			servo[servo1] = 10;
		} else {
			servo[servo1] = 135;
		}
  }
}
