#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    testServo,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    testServo2,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	int y1, y2;
	while (true)
	{
		getJoystickSettings(joystick);
		y1 = joystick.joy1_y1 + 128;
		y2 = joystick.joy1_y2 + 128;
		servo[testServo] = y1;
		servo[testServo2] = y2;
	}
}
